### ISSUE TITLE
ERC20 Adapter (protocol)

### ISSUE THREAD

**Issue by neodaoist** [valorem-labs-inc/valorem-erc20-adapter#5]
As a **Valorem User,**
I want **to use Valorem Core options and claims as long and short ERC20 tokens,**
so that **I can transact within the broader DeFi ecosystem which widely supports ERC20.**

**Acceptance Criteria**
- Should be able to deploy ERC20 Long and Short Adapter contracts for a given Core Option Type
- Router/Gateway functionality
  - Should be able to write new ERC20 Long and Short positions against the Router/Gateway contract
  - Should be able to wrap Core Options into ERC20 Longs (timebound)
  - Should be able to unwrap ERC20 Longs into Core Options (timebound)
- Long functionality
  - Should be able to check the position of an ERC20 Long(s)
  - Should be able to exercise an ERC20 Long(s) (timebound)
- Short functionality
  - Should be able to check the position of an ERC20 Short(s)
  - Should be able to redeem an ERC20 Short(s) (timebound)

**Notes**
- Q — where does the wrap/unwrap functionality go, on the Router/Gateway or the ERC20 Long itself? pros/cons to either approach

**Comment by neodaoist** [comment]
Created placeholder and moved in progress

**Comment by 0xAlcibiades** [comment]
@neodaoist co-assigning you here, but let's get all the nice stuff from the figjam in here.

**Comment by 0xAlcibiades** [comment]
Closing this for now as wont do.
